os:
  edit: nvim --server /tmp/nvim-server-$(tmux display-message -p '#S-#I-#P').pipe --remote-send "<cmd>lua require('utils.lazygit-open-file')('{{filename}}', '{{line}}')<CR>"
  open: nvim --server /tmp/nvim-server-$(tmux display-message -p '#S-#I-#P').pipe --remote-send "<cmd>lua require('utils.lazygit-open-file')('{{filename}}', '{{line}}')<CR>"
